AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SampleQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SampleQueue
Outputs:
  SampleQueueARN:
    Value:
      Fn::GetAtt:
      - SampleQueue
      - Arn
